# Generated by Django 3.1.3 on 2020-11-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='text',
            new_name='title',
        ),
    ]
